{
  "formatVersion": "1.1",
  "component": {
    "group": "com.badlogicgames.gdx",
    "module": "gdx",
    "version": "1.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.1",
      "buildId": "7yblorcyybesnnduy5fha6p3na"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-jnigen-loader",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "gdx-1.11.0.jar",
          "url": "gdx-1.11.0.jar",
          "size": 2007778,
          "sha512": "168b715e7b3a6e0dedb36ebdfd25635e4f94f5d596022668f51793f16cad1761dbd8023cd4f9ab1ec102b4eaab2c7418a2880efbe72ded6f402fdab8b6dfa053",
          "sha256": "23153c67e19560644e0fa1235232b5d85ee41cf289281c2da7ec8c28e35750b9",
          "sha1": "ffe1206d1004cd9e40027e28964be0fea0399af7",
          "md5": "f0c20dc3ec95b151aa1facd78d75e005"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.badlogicgames.gdx",
          "module": "gdx-jnigen-loader",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "gdx-1.11.0.jar",
          "url": "gdx-1.11.0.jar",
          "size": 2007778,
          "sha512": "168b715e7b3a6e0dedb36ebdfd25635e4f94f5d596022668f51793f16cad1761dbd8023cd4f9ab1ec102b4eaab2c7418a2880efbe72ded6f402fdab8b6dfa053",
          "sha256": "23153c67e19560644e0fa1235232b5d85ee41cf289281c2da7ec8c28e35750b9",
          "sha1": "ffe1206d1004cd9e40027e28964be0fea0399af7",
          "md5": "f0c20dc3ec95b151aa1facd78d75e005"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gdx-1.11.0-javadoc.jar",
          "url": "gdx-1.11.0-javadoc.jar",
          "size": 4028035,
          "sha512": "5c4551a7b6526fd15716c191a05760bf654f40258489027b344248fa97c5e8b492a3172c5231f068ee121176ec8bf19997e1b368f43eb48b3dc97e3365213879",
          "sha256": "5dbd29c986521ea3eb68b6b0c555cf78e80b7641fb9fde2b7203c91d674a058e",
          "sha1": "0f14119fc8ded4d354ed8423469c4cf610f41312",
          "md5": "af7e0c71e2f5b18d51a10629c3f1b808"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gdx-1.11.0-sources.jar",
          "url": "gdx-1.11.0-sources.jar",
          "size": 1341296,
          "sha512": "490d032207ed0700c6d9dcefcb96d90b7d67b7619948c32fe8463159bf164114e69855c04194c8b20bbda6c3d6cdfc705856f6089f020bced52c27209c37b4ae",
          "sha256": "de9591e25a0f1078cdfc7712716eeb016cb25427b3d864d57859328f85df76fd",
          "sha1": "ea3e9eccc5c09636f405e345039b62376465a6f4",
          "md5": "ebda2bca2f4da3c296fa7544114c7a9d"
        }
      ]
    }
  ]
}
